<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Bahan;

class DummyBahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // TODO: Replace this array with JSON output from GPT
        // Copy-paste the JSON array generated by GPT here
        $bahans = [
            // Example structure:
            // [
            //     "name" => "Bawang merah",
            //     "units" => ["buah", "siung", "gram", "ons"]
            // ],
            // [
            //     "name" => "Cabai merah",
            //     "units" => ["buah", "gram", "ons", "potong"]
            // ],
            // ... paste GPT result here (convert to PHP array format)
        ];

        // Uncomment this section after adding the data above
        /*
        foreach($bahans as $bahan) {
            Bahan::create([
                'name' => $bahan['name'],
                'units' => json_encode($bahan['units'])
            ]);
        }

        $this->command->info('Successfully imported ' . count($bahans) . ' bahan items');
        */
        
        $this->command->warn('No data imported. Please add bahan data to the $bahans array first.');
        $this->command->info('Steps:');
        $this->command->info('1. Use the GPT prompt from GPT_PROMPT_BAHAN.txt');
        $this->command->info('2. Copy the JSON result to the $bahans array above (convert to PHP array)');
        $this->command->info('3. Uncomment the foreach loop');
        $this->command->info('4. Run: php artisan db:seed --class=DummyBahanSeeder');
    }
}
